import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import twitterGetUrl from "twitter-url-direct";

export default function Home() {
  const [tweet, setTweet] = useState(null);
  const [video, setVideo] = useState(null);

  const getVideoURL = async () => {
    const videoUrl = await twitterGetUrl(tweet);
    setVideo(videoUrl);
  };

  console.log(tweet);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Get URL from tweet</h1>

        <div>
          <input onChange={(e) => setTweet(e.target.value)} type="text" />
          <button onClick={getVideoURL}>get direct url</button>
        </div>

        <p style={{ color: "green" }}>{video}</p>
      </main>
    </div>
  );
}
